# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AWS Airflow Executor Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest apache-airflow boto3 pylint isort marshmallow
    - name: Lint with Pylint
      run: |
        pylint --fail-under=9 ./airflow_aws_executors
    - name: Lint with ISort
      run: |
        isort -c -rc ./airflow_aws_executors
    - name: Test with pytest
      run: |
        pytest
      env:
        AIRFLOW__BATCH__REGION: us-west-1 
        AIRFLOW__BATCH__JOB_NAME: some-job-name 
        AIRFLOW__BATCH__JOB_QUEUE: some-job-queue 
        AIRFLOW__BATCH__JOB_DEFINITION: some-job-def 
        AIRFLOW__ECS_FARGATE__REGION: us-west-1 
        AIRFLOW__ECS_FARGATE__CLUSTER: some-cluster 
        AIRFLOW__ECS_FARGATE__CONTAINER_NAME: some-container-name 
        AIRFLOW__ECS_FARGATE__TASK_DEFINITION: some-task-def 
        AIRFLOW__ECS_FARGATE__LAUNCH_TYPE: FARGATE 
        AIRFLOW__ECS_FARGATE__PLATFORM_VERSION: LATEST 
        AIRFLOW__ECS_FARGATE__ASSIGN_PUBLIC_IP: DISABLED 
        AIRFLOW__ECS_FARGATE__SECURITY_GROUPS: SG1,SG2 
        AIRFLOW__ECS_FARGATE__SUBNETS: SUB1,SUB2
